
POST http://localhost:4000/api/auth/signin HTTP/1.1
Content-Type: application/json

{
    "username": "edsonrosas",
    "password": "edsonrosas"
}

###
POST http://localhost:4000/api/elections/7 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjU1MjYyNDM4LCJleHAiOjE2NTUzNDg4Mzh9.oxpJZLyc0zi0miC0Q_Eb2_ab2dXXvvt8euDyWmibuyk
Content-Type: application/json

{
    "postulation_StartDate":"2022-06-05",
    "postulation_EndDate": "2022-06-19",
    "date": "2022-06-29"
}

###
GET http://localhost:4000/api/elections/exist/7 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjU1MjYyNDM4LCJleHAiOjE2NTUzNDg4Mzh9.oxpJZLyc0zi0miC0Q_Eb2_ab2dXXvvt8euDyWmibuyk
###
GET http://localhost:4000/api/elections/2/postulants HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjU1MjYyNDM4LCJleHAiOjE2NTUzNDg4Mzh9.oxpJZLyc0zi0miC0Q_Eb2_ab2dXXvvt8euDyWmibuyk
