POST http://localhost:4000/api/elections/1 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjUzMjAwODQ3LCJleHAiOjE2NTMyODcyNDd9.1bw2egP6wn1wC7rS_rJdVUpeorQQi9QWkL7NoDZq4Fk
Content-Type: application/json

{
    "postulation_StartDate":"2022-05-20",
    "postulation_EndDate": "2022-05-21",
    "date": "2022-05-22" 
}

###
GET http://localhost:4000/api/elections/exist/1 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjUzMTkxNDcxLCJleHAiOjE2NTMyNzc4NzF9.Smwra-5fKb-5hfrL0Ozb_0IH5jhQMJHbesdo7vmshl8

###
GET http://localhost:4000/api/elections/1/postulants HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjUzMjAwMTU0LCJleHAiOjE2NTMyODY1NTR9.4BVW1ClKOZIPGLQmMiC9ZPFPU2M_EU5dqjsfzUqyR_A