POST http://localhost:4000/api/organizations/2 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjUzMjAwODQ3LCJleHAiOjE2NTMyODcyNDd9.1bw2egP6wn1wC7rS_rJdVUpeorQQi9QWkL7NoDZq4Fk
Content-Type: application/json

{
    "name":"Estado plurinacional de Bolivia",
    "description": "lorem ipsum",
    "reach": "Nacional" 
}
###
POST http://localhost:4000/api/organizations/2 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjUzMjAwODQ3LCJleHAiOjE2NTMyODcyNDd9.1bw2egP6wn1wC7rS_rJdVUpeorQQi9QWkL7NoDZq4Fk
Content-Type: application/json

{
    "name":"OTB Villa Moderna",
    "description": "lorem ipsum",
    "reach": "Vecinal"
}


###
POST  http://localhost:4000/api/organizations/2/users HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjUyMjMzODE4LCJleHAiOjE2NTIzMjAyMTh9.ETmNAF3inX181bDrRfTD7hG9HjFcE0RSXMzJqQ7F9Pw
Content-Type: application/json

{
    "users": [1,3]
}

###
GET http://localhost:4000/api/organizations/1/users HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjUzMjAwMTU0LCJleHAiOjE2NTMyODY1NTR9.4BVW1ClKOZIPGLQmMiC9ZPFPU2M_EU5dqjsfzUqyR_A
