POST http://localhost:4000/api/organizations/2 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjUzMTkxNDcxLCJleHAiOjE2NTMyNzc4NzF9.Smwra-5fKb-5hfrL0Ozb_0IH5jhQMJHbesdo7vmshl8
Content-Type: application/json

{
    "name":"Estado plurinacional de Bolivia",
    "description": "lorem ipsum",
    "reach": "Nacional" 
}
###
POST http://localhost:4000/api/organizations/2 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjUzMTkxNDcxLCJleHAiOjE2NTMyNzc4NzF9.Smwra-5fKb-5hfrL0Ozb_0IH5jhQMJHbesdo7vmshl8
Content-Type: application/json

{
    "name":"OTB Villa Moderna",
    "description": "lorem ipsum",
    "reach": "Vecinal"
}


###
POST  http://localhost:4000/api/organizations/2/users HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjUyMjMzODE4LCJleHAiOjE2NTIzMjAyMTh9.ETmNAF3inX181bDrRfTD7hG9HjFcE0RSXMzJqQ7F9Pw
Content-Type: application/json

{
    "users": [1,3]
}

###
GET http://localhost:4000/api/organizations/3/users HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjUyNzU5NzA1LCJleHAiOjE2NTI4NDYxMDV9.K83uB8_CO-MmTZfTpe_mi6YHTKM4YfPeLPLdPRjwB-4