POST http://localhost:4000/api/postulants/2/5 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjUzNDQxNDYxLCJleHAiOjE2NTM1Mjc4NjF9.tPOl4Zo-_aSosQ6PxUQyeyD6nNBfUgQMd7E7Rz5g2Ko
Content-Type: application/json

{
    "nameFront":"Algun frente",
    "description": "lorem ipsum" 
}

### saber si el postulante es candidato
GET http://localhost:4000/api/postulants/iscandidate/2/1 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjUzNDQxNDYxLCJleHAiOjE2NTM1Mjc4NjF9.tPOl4Zo-_aSosQ6PxUQyeyD6nNBfUgQMd7E7Rz5g2Ko

###
PUT http://localhost:4000/api/postulants/votes/2 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjUzNDQxNDYxLCJleHAiOjE2NTM1Mjc4NjF9.tPOl4Zo-_aSosQ6PxUQyeyD6nNBfUgQMd7E7Rz5g2Ko
Content-Type: application/json

{
    "users": [{"idUser": 5, "votes": 12},{"idUser":3, "votes": 10},{"idUser":4, "votes": 17}]
}