
POST http://localhost:4000/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "name":"edson",
    "last_name":"rosas",
    "username":"edsonrosaxasdfzs",
    "email":"edson1@gmailzxcasdf.com",
    "password":"edson123"
}

###
POST http://localhost:4000/api/auth/signin HTTP/1.1
Content-Type: application/json

{
    "username": "edsonrosas",
    "password": "edsonrosas"
}

###
GET http://localhost:4000/api/users HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjUyMjQwMzAxLCJleHAiOjE2NTIzMjY3MDF9.eiKWnY5DZcTj2qkWbub-AFwT7zO6zAKiMXKD0Lizlbc

###
GET http://localhost:4000/api/users/1/organizations HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjU1MjYyNDM4LCJleHAiOjE2NTUzNDg4Mzh9.oxpJZLyc0zi0miC0Q_Eb2_ab2dXXvvt8euDyWmibuyk
###
PUT http://localhost:4000/api/users/3/acceptElection/7 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjU1MjYyNDM4LCJleHAiOjE2NTUzNDg4Mzh9.oxpJZLyc0zi0miC0Q_Eb2_ab2dXXvvt8euDyWmibuyk
Content-Type: application/json

{

}

###
PUT http://localhost:4000/api/users/1/voteElection/7 HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjU1MjYyNDM4LCJleHAiOjE2NTUzNDg4Mzh9.oxpJZLyc0zi0miC0Q_Eb2_ab2dXXvvt8euDyWmibuyk
Content-Type: application/json
 
 {

 }
